name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Checkout 
        uses: actions/checkout@v2
      - name: List files after checkout 
        run: |
          pwd
          ls -a
      - name: Simple Javascrip Action
        id: greed
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greed: Marina
      - name: Log Greeding Tiime
        run: echo "${{ steps.greed.outputs.time }}"